### PR TITLE
fix(ui): derive isProject in sidebar from project context

### PR DESCRIPTION
**Pull request by ka1kqi**
## Summary

`main` currently crashes the layout on every page with `Uncaught ReferenceError: isProject is not defined` at `sidebar.tsx`. The sidebar-upgrade and workspace-settings-nav branches merged with a semantic conflict: the upgrade-button gating references `isProject`, while the hardening pass moved that logic into `getProjectContext()` (imported but never called), leaving the variable undefined.

One-line fix: derive `const { isProject } = getProjectContext(pathname)` alongside the existing route-param context.

## Testing

- `tsc --noEmit` goes from `error TS2304: Cannot find name 'isProject'` to clean.
- Verified on the local stack that pages render again (the layout previously crashed with the dev overlay's "This page couldn't load").

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---
## Summary by cubic
Fixes a layout crash by deriving `isProject` from project context in the sidebar. The sidebar now calls `getProjectContext(pathname)` and uses its `isProject` flag to gate the upgrade button, removing the undefined variable that broke every page.

<sup>Written for commit fc9bd870b66940bbf2aa2a0396635b56e8fa79dc. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/traceroot-ai/traceroot/pull/1127?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by ka1kqi** [comment]
Folding this into #1126, which carries the same fix.
